name: Build Factorio Mod

on:
  push:
    branches:
      - master

jobs:
  build-mod:
    name: Build Mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Mod
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: validate
          mod-folder: src

      - name: Create zip
        uses: TheBrutalX/factorio-mod-uploader-action@v2
        with:
          action: compress
          mod-folder: src

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: duct_tape_zip
          path: ${{ env.ZIP_FILE}}

